spring.application.name=CharityDonation
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port=8080

# Thông tin DB c?a b?n
spring.datasource.url=jdbc:mysql://localhost:3306/charity_db
spring.datasource.username=root
spring.datasource.password=1989
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# T? ??ng t?o b?ng t? code Java (Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true